---
AWSTemplateFormatVersion: '2010-09-09'
Description: A complete demo stack for the rate-based rule provider including cloudfront, webacl, and rules.

Resources:
  SqlInjectionMatchSetTestPredicate:
    Type: AWS::WAF::SqlInjectionMatchSet
    Properties:
      Name: completedemosqlinjectionmatchset
      SqlInjectionMatchTuples:
      -
        FieldToMatch:
          Type: URI
        TextTransformation: NONE
  XssMatchSetTrestPredicate:
    Type: AWS::WAF::XssMatchSet
    Properties:
      Name: completedemosizecontraintset
      XssMatchTuples:
      -
        FieldToMatch:
          Type: BODY
        TextTransformation: NONE
  RateBasedRuleWithPredicate1:
    Type: Custom::RateBasedRule
    Properties:
      Name: completedemoratebasedrulepredicate1
      MetricName: completedemoratebasedrulepredicate1metric
      RateKey: IP
      RateLimit: 3245
      MatchPredicates:
      -
        Negated: False
        Type: XssMatch
        DataId: !Ref XssMatchSetTrestPredicate
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-waf-provider'
  RateBasedRuleWithPredicate2:
    DependsOn: RateBasedRuleWithPredicate1
    Type: Custom::RateBasedRule
    Properties:
      Name: completedemoratebasedrulepredicate2
      MetricName: completedemoratebasedrulepredicate2metric
      RateKey: IP
      RateLimit: 2800
      MatchPredicates:
      -
        Negated: False
        Type: SqlInjectionMatch
        DataId: !Ref SqlInjectionMatchSetTestPredicate
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-waf-provider'
  S3Bucket:
    Type: AWS::S3::Bucket

Outputs:
  RateBasedRuleName1:
    Value: !GetAtt RateBasedRuleWithPredicate1.Name