---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo stack for the rate-based rule provider

Resources:
  RateBasedRule:
    Type: Custom::RateBasedRule
    Properties:
      Name: ratebasedrule
      MetricName: ratebasedrulemetric
      RateKey: IP
      RateLimit: 4500
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-waf-provider'

Outputs:
  RateBasedRuleName:
    Value: !Ref RateBasedRule