---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo stack for the rate-based rule provider

Resources:
  RateBasedRuleWithPredicate:
    Type: Custom::RateBasedRule
    Properties:
      Name: RateBasedRulePredicate1
      MetricName: ratebasedrulepredicate1metric
      RateKey: IP
      RateLimit: 3245
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-waf-provider'
