---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo stack for the rate-based rule provider

Resources:
  RateBasedRuleWithPredicate:
    Type: Custom::RateBasedRule
    Properties:
      Name: WafRateBasedRulePredicate2
      MetricName: wafratebasedrulepredicatemetric
      RateKey: IP
      RateLimit: 3245
      MatchPredicates:
        -
          Negated: false
          Type: IPMatch
          DataId: ipsettestpredicate
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-waf-provider'